// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Session struct {
	ID              int64         `json:"id"`
	StartTime       time.Time     `json:"start_time"`
	DurationSeconds sql.NullInt64 `json:"duration_seconds"`
	TaskID          int64         `json:"task_id"`
}

type Task struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	ColorHex    sql.NullString `json:"color_hex"`
	Completed   sql.NullBool   `json:"completed"`
	DailyTarget sql.NullInt64  `json:"daily_target"`
}
