// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteTask(ctx context.Context, id int64) error
	GetDailyTaskDurations(ctx context.Context) ([]GetDailyTaskDurationsRow, error)
	GetTaskDurationForPeriod(ctx context.Context, arg GetTaskDurationForPeriodParams) (sql.NullFloat64, error)
	GetTasks(ctx context.Context) ([]Task, error)
	StartSession(ctx context.Context, arg StartSessionParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
