// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getDailyTaskDurations = `-- name: GetDailyTaskDurations :many
SELECT task_id, SUM(duration_seconds) as total_duration
FROM sessions
WHERE DATE(start_time) = CURRENT_DATE
GROUP BY task_id
`

type GetDailyTaskDurationsRow struct {
	TaskID        int64           `json:"task_id"`
	TotalDuration sql.NullFloat64 `json:"total_duration"`
}

func (q *Queries) GetDailyTaskDurations(ctx context.Context) ([]GetDailyTaskDurationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyTaskDurations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyTaskDurationsRow
	for rows.Next() {
		var i GetDailyTaskDurationsRow
		if err := rows.Scan(&i.TaskID, &i.TotalDuration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskDurationForPeriod = `-- name: GetTaskDurationForPeriod :one
SELECT SUM(duration_seconds) as total_duration
FROM sessions
WHERE task_id = ?
AND start_time >= ?
AND start_time <= ?
`

type GetTaskDurationForPeriodParams struct {
	TaskID      int64     `json:"task_id"`
	StartTime   time.Time `json:"start_time"`
	StartTime_2 time.Time `json:"start_time_2"`
}

func (q *Queries) GetTaskDurationForPeriod(ctx context.Context, arg GetTaskDurationForPeriodParams) (sql.NullFloat64, error) {
	row := q.db.QueryRowContext(ctx, getTaskDurationForPeriod, arg.TaskID, arg.StartTime, arg.StartTime_2)
	var total_duration sql.NullFloat64
	err := row.Scan(&total_duration)
	return total_duration, err
}

const startSession = `-- name: StartSession :one
INSERT INTO sessions (start_time, task_id)
VALUES (?, ?)
RETURNING id, start_time, duration_seconds, task_id
`

type StartSessionParams struct {
	StartTime time.Time `json:"start_time"`
	TaskID    int64     `json:"task_id"`
}

func (q *Queries) StartSession(ctx context.Context, arg StartSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, startSession, arg.StartTime, arg.TaskID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.DurationSeconds,
		&i.TaskID,
	)
	return i, err
}
