// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (name, color_hex, daily_target, completed)
VALUES (?, ?, ?, FALSE)
RETURNING id, name, color_hex, completed, daily_target
`

type CreateTaskParams struct {
	Name        string         `json:"name"`
	ColorHex    sql.NullString `json:"color_hex"`
	DailyTarget sql.NullInt64  `json:"daily_target"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.Name, arg.ColorHex, arg.DailyTarget)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ColorHex,
		&i.Completed,
		&i.DailyTarget,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTasks = `-- name: GetTasks :many
SELECT id, name, color_hex, completed, daily_target
FROM tasks
ORDER BY id
`

func (q *Queries) GetTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ColorHex,
			&i.Completed,
			&i.DailyTarget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
